# Copyright 2017 Open Source Robotics Foundation
# Distributed under the terms of the BSD license

DESCRIPTION = "hector_geotiff_plugins contains plugins that extend geotiff maps generated by he"
AUTHOR = "OSRF"
SECTION = "devel"
LICENSE = "BSD"
LIC_FILES_CHKSUM = "file://package.xml;beginline=13;endline=13;md5=2c00b8d2854109dbebef7818b4dae1e2"

DEPENDS = "catkin-native hector-geotiff hector-nav-msgs"
SRC_URI = "https://github.com/tu-darmstadt-ros-pkg-gbp/hector_slam-release/archive/release/kinetic/hector_geotiff_plugins/0.3.5-0.tar.gz;downloadfilename=${ROS_SP}.tar.gz"

SRC_URI[md5sum] = "7e28314a62d368c176dcc8f2519fc8e1"
SRC_URI[sha256sum] = "61f68b9f084ee21ddac3e1838d828f6dd24e321816a70f6486fbe19c6f342554"
S = "${WORKDIR}/hector_slam-release-release-kinetic-hector_geotiff_plugins-0.3.5-0"

inherit catkin
